//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}ProcessSpecification"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Role"/&gt;
 *         &lt;element name="ApplicationCertificateRef" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}CertificateRef.type" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="ApplicationSecurityDetailsRef" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}SecurityDetailsRef.type" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}ServiceBinding"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processSpecification",
    "role",
    "applicationCertificateRef",
    "applicationSecurityDetailsRef",
    "serviceBinding"
})
@XmlRootElement(name = "CollaborationRole")
public class CollaborationRole
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ProcessSpecification", required = true)
    @NotNull
    protected ProcessSpecification processSpecification;
    @XmlElement(name = "Role", required = true)
    @NotNull
    protected Role role;
    @XmlElement(name = "ApplicationCertificateRef")
    @NotNull
    protected List<@NotNull CertificateRefType> applicationCertificateRef;
    @XmlElement(name = "ApplicationSecurityDetailsRef")
    protected SecurityDetailsRefType applicationSecurityDetailsRef;
    @XmlElement(name = "ServiceBinding", required = true)
    @NotNull
    protected ServiceBinding serviceBinding;

    /**
     * Gets the value of the processSpecification property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessSpecification }
     *     
     */
    @NotNull
    public ProcessSpecification getProcessSpecification() {
        return processSpecification;
    }

    /**
     * Sets the value of the processSpecification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessSpecification }
     *     
     */
    public void setProcessSpecification(
        @NotNull
        ProcessSpecification value) {
        this.processSpecification = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link Role }
     *     
     */
    @NotNull
    public Role getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link Role }
     *     
     */
    public void setRole(
        @NotNull
        Role value) {
        this.role = value;
    }

    /**
     * Gets the value of the applicationCertificateRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationCertificateRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationCertificateRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CertificateRefType }
     * 
     * 
     */
    @NotNull
    public List<@NotNull CertificateRefType> getApplicationCertificateRef() {
        if (applicationCertificateRef == null) {
            applicationCertificateRef = new ArrayList<CertificateRefType>();
        }
        return this.applicationCertificateRef;
    }

    /**
     * Gets the value of the applicationSecurityDetailsRef property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityDetailsRefType }
     *     
     */
    public SecurityDetailsRefType getApplicationSecurityDetailsRef() {
        return applicationSecurityDetailsRef;
    }

    /**
     * Sets the value of the applicationSecurityDetailsRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityDetailsRefType }
     *     
     */
    public void setApplicationSecurityDetailsRef(SecurityDetailsRefType value) {
        this.applicationSecurityDetailsRef = value;
    }

    /**
     * Gets the value of the serviceBinding property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceBinding }
     *     
     */
    @NotNull
    public ServiceBinding getServiceBinding() {
        return serviceBinding;
    }

    /**
     * Sets the value of the serviceBinding property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceBinding }
     *     
     */
    public void setServiceBinding(
        @NotNull
        ServiceBinding value) {
        this.serviceBinding = value;
    }

}
