//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for messageOrderSemantics.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="messageOrderSemantics.type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name"&gt;
 *     &lt;enumeration value="Guaranteed"/&gt;
 *     &lt;enumeration value="NotGuaranteed"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "messageOrderSemantics.type")
@XmlEnum
public enum MessageOrderSemanticsType {

    @XmlEnumValue("Guaranteed")
    GUARANTEED("Guaranteed"),
    @XmlEnumValue("NotGuaranteed")
    NOT_GUARANTEED("NotGuaranteed");
    private final String value;

    MessageOrderSemanticsType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MessageOrderSemanticsType fromValue(String v) {
        for (MessageOrderSemanticsType c: MessageOrderSemanticsType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
