//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.oasis-open.org/committees/ebxml-msg/schema/msg-header-2_0.xsd", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
@com.github.labai.jsr305x.api.NullableByDefault
package org.oasis_open.committees.ebxml_msg.schema.msg_header_2_0;
