//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actor.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="actor.type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="urn:oasis:names:tc:ebxml-msg:actor:nextMSH"/&gt;
 *     &lt;enumeration value="urn:oasis:names:tc:ebxml-msg:actor:toPartyMSH"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "actor.type")
@XmlEnum
public enum ActorType {

    @XmlEnumValue("urn:oasis:names:tc:ebxml-msg:actor:nextMSH")
    URN_OASIS_NAMES_TC_EBXML_MSG_ACTOR_NEXT_MSH("urn:oasis:names:tc:ebxml-msg:actor:nextMSH"),
    @XmlEnumValue("urn:oasis:names:tc:ebxml-msg:actor:toPartyMSH")
    URN_OASIS_NAMES_TC_EBXML_MSG_ACTOR_TO_PARTY_MSH("urn:oasis:names:tc:ebxml-msg:actor:toPartyMSH");
    private final String value;

    ActorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActorType fromValue(String v) {
        for (ActorType c: ActorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
