//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}SignatureTransforms" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}EncryptionTransforms" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}idref use="required""/&gt;
 *       &lt;attribute name="excludedFromSignature" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="minOccurs" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *       &lt;attribute name="maxOccurs" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "signatureTransforms",
    "encryptionTransforms"
})
@XmlRootElement(name = "Constituent")
public class Constituent
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SignatureTransforms")
    protected SignatureTransforms signatureTransforms;
    @XmlElement(name = "EncryptionTransforms")
    protected EncryptionTransforms encryptionTransforms;
    @XmlAttribute(name = "idref", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @NotNull
    protected Object idref;
    @XmlAttribute(name = "excludedFromSignature", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd")
    protected Boolean excludedFromSignature;
    @XmlAttribute(name = "minOccurs", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger minOccurs;
    @XmlAttribute(name = "maxOccurs", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger maxOccurs;

    /**
     * Gets the value of the signatureTransforms property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureTransforms }
     *     
     */
    public SignatureTransforms getSignatureTransforms() {
        return signatureTransforms;
    }

    /**
     * Sets the value of the signatureTransforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureTransforms }
     *     
     */
    public void setSignatureTransforms(SignatureTransforms value) {
        this.signatureTransforms = value;
    }

    /**
     * Gets the value of the encryptionTransforms property.
     * 
     * @return
     *     possible object is
     *     {@link EncryptionTransforms }
     *     
     */
    public EncryptionTransforms getEncryptionTransforms() {
        return encryptionTransforms;
    }

    /**
     * Sets the value of the encryptionTransforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link EncryptionTransforms }
     *     
     */
    public void setEncryptionTransforms(EncryptionTransforms value) {
        this.encryptionTransforms = value;
    }

    /**
     * Gets the value of the idref property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @NotNull
    public Object getIdref() {
        return idref;
    }

    /**
     * Sets the value of the idref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdref(
        @NotNull
        Object value) {
        this.idref = value;
    }

    /**
     * Gets the value of the excludedFromSignature property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isExcludedFromSignature() {
        if (excludedFromSignature == null) {
            return false;
        } else {
            return excludedFromSignature;
        }
    }

    /**
     * Sets the value of the excludedFromSignature property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExcludedFromSignature(Boolean value) {
        this.excludedFromSignature = value;
    }

    /**
     * Gets the value of the minOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinOccurs() {
        return minOccurs;
    }

    /**
     * Sets the value of the minOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinOccurs(BigInteger value) {
        this.minOccurs = value;
    }

    /**
     * Gets the value of the maxOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxOccurs() {
        return maxOccurs;
    }

    /**
     * Sets the value of the maxOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxOccurs(BigInteger value) {
        this.maxOccurs = value;
    }

}
