//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}MessagingCharacteristics"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="channelId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *       &lt;attribute name="transportId" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="docExchangeId" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messagingCharacteristics"
})
@XmlRootElement(name = "DeliveryChannel")
public class DeliveryChannel
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "MessagingCharacteristics", required = true)
    @NotNull
    protected MessagingCharacteristics messagingCharacteristics;
    @XmlAttribute(name = "channelId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @NotNull
    protected String channelId;
    @XmlAttribute(name = "transportId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @NotNull
    protected Object transportId;
    @XmlAttribute(name = "docExchangeId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @NotNull
    protected Object docExchangeId;

    /**
     * Gets the value of the messagingCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link MessagingCharacteristics }
     *     
     */
    @NotNull
    public MessagingCharacteristics getMessagingCharacteristics() {
        return messagingCharacteristics;
    }

    /**
     * Sets the value of the messagingCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessagingCharacteristics }
     *     
     */
    public void setMessagingCharacteristics(
        @NotNull
        MessagingCharacteristics value) {
        this.messagingCharacteristics = value;
    }

    /**
     * Gets the value of the channelId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @NotNull
    public String getChannelId() {
        return channelId;
    }

    /**
     * Sets the value of the channelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChannelId(
        @NotNull
        String value) {
        this.channelId = value;
    }

    /**
     * Gets the value of the transportId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @NotNull
    public Object getTransportId() {
        return transportId;
    }

    /**
     * Sets the value of the transportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setTransportId(
        @NotNull
        Object value) {
        this.transportId = value;
    }

    /**
     * Gets the value of the docExchangeId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @NotNull
    public Object getDocExchangeId() {
        return docExchangeId;
    }

    /**
     * Sets the value of the docExchangeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDocExchangeId(
        @NotNull
        Object value) {
        this.docExchangeId = value;
    }

}
