//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.io.Serializable;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ProcessingCapabilities"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="parse" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *                 &lt;attribute name="generate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="CompositeList" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded"&gt;
 *                   &lt;element name="Encapsulation"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Constituent"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attGroup ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}pkg.grp"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Composite"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Constituent" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attGroup ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}pkg.grp"/&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}id use="required""/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "processingCapabilities",
    "compositeList"
})
@XmlRootElement(name = "Packaging")
public class Packaging
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "ProcessingCapabilities", required = true)
    @NotNull
    protected Packaging.ProcessingCapabilities processingCapabilities;
    @XmlElement(name = "CompositeList", required = true)
    @NotNull
    protected List<@NotNull CompositeList> compositeList;
    @XmlAttribute(name = "id", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @NotNull
    protected String id;

    /**
     * Gets the value of the processingCapabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Packaging.ProcessingCapabilities }
     *     
     */
    @NotNull
    public Packaging.ProcessingCapabilities getProcessingCapabilities() {
        return processingCapabilities;
    }

    /**
     * Sets the value of the processingCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Packaging.ProcessingCapabilities }
     *     
     */
    public void setProcessingCapabilities(
        @NotNull
        Packaging.ProcessingCapabilities value) {
        this.processingCapabilities = value;
    }

    /**
     * Gets the value of the compositeList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compositeList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompositeList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Packaging.CompositeList }
     * 
     * 
     */
    @NotNull
    public List<@NotNull CompositeList> getCompositeList() {
        if (compositeList == null) {
            compositeList = new ArrayList<Packaging.CompositeList>();
        }
        return this.compositeList;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @NotNull
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(
        @NotNull
        String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded"&gt;
     *         &lt;element name="Encapsulation"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Constituent"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attGroup ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}pkg.grp"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Composite"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Constituent" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attGroup ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}pkg.grp"/&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "encapsulationOrComposite"
    })
    public static class CompositeList
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlElements({
            @XmlElement(name = "Encapsulation", type = Packaging.CompositeList.Encapsulation.class),
            @XmlElement(name = "Composite", type = Packaging.CompositeList.Composite.class)
        })
        @NotNull
        protected List<@NotNull Serializable> encapsulationOrComposite;

        /**
         * Gets the value of the encapsulationOrComposite property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the encapsulationOrComposite property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEncapsulationOrComposite().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Packaging.CompositeList.Composite }
         * {@link Packaging.CompositeList.Encapsulation }
         * 
         * 
         */
        @NotNull
        public List<@NotNull Serializable> getEncapsulationOrComposite() {
            if (encapsulationOrComposite == null) {
                encapsulationOrComposite = new ArrayList<Serializable>();
            }
            return this.encapsulationOrComposite;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Constituent" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attGroup ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}pkg.grp"/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "constituent"
        })
        public static class Composite implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "Constituent", required = true)
            @NotNull
            protected List<@NotNull Constituent> constituent;
            @XmlAttribute(name = "id", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            @NotNull
            protected String id;
            @XmlAttribute(name = "mimetype", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
            @NotNull
            protected String mimetype;
            @XmlAttribute(name = "mimeparameters", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd")
            protected String mimeparameters;

            /**
             * Gets the value of the constituent property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the constituent property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getConstituent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Constituent }
             * 
             * 
             */
            @NotNull
            public List<@NotNull Constituent> getConstituent() {
                if (constituent == null) {
                    constituent = new ArrayList<Constituent>();
                }
                return this.constituent;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @NotNull
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(
                @NotNull
                String value) {
                this.id = value;
            }

            /**
             * Gets the value of the mimetype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @NotNull
            public String getMimetype() {
                return mimetype;
            }

            /**
             * Sets the value of the mimetype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMimetype(
                @NotNull
                String value) {
                this.mimetype = value;
            }

            /**
             * Gets the value of the mimeparameters property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMimeparameters() {
                return mimeparameters;
            }

            /**
             * Sets the value of the mimeparameters property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMimeparameters(String value) {
                this.mimeparameters = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Constituent"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;attGroup ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}pkg.grp"/&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "constituent"
        })
        public static class Encapsulation implements Serializable
        {

            private final static long serialVersionUID = 1L;
            @XmlElement(name = "Constituent", required = true)
            @NotNull
            protected Constituent constituent;
            @XmlAttribute(name = "id", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlID
            @XmlSchemaType(name = "ID")
            @NotNull
            protected String id;
            @XmlAttribute(name = "mimetype", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
            @NotNull
            protected String mimetype;
            @XmlAttribute(name = "mimeparameters", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd")
            protected String mimeparameters;

            /**
             * Gets the value of the constituent property.
             * 
             * @return
             *     possible object is
             *     {@link Constituent }
             *     
             */
            @NotNull
            public Constituent getConstituent() {
                return constituent;
            }

            /**
             * Sets the value of the constituent property.
             * 
             * @param value
             *     allowed object is
             *     {@link Constituent }
             *     
             */
            public void setConstituent(
                @NotNull
                Constituent value) {
                this.constituent = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @NotNull
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(
                @NotNull
                String value) {
                this.id = value;
            }

            /**
             * Gets the value of the mimetype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            @NotNull
            public String getMimetype() {
                return mimetype;
            }

            /**
             * Sets the value of the mimetype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMimetype(
                @NotNull
                String value) {
                this.mimetype = value;
            }

            /**
             * Gets the value of the mimeparameters property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMimeparameters() {
                return mimeparameters;
            }

            /**
             * Sets the value of the mimeparameters property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMimeparameters(String value) {
                this.mimeparameters = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="parse" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *       &lt;attribute name="generate" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ProcessingCapabilities
        implements Serializable
    {

        private final static long serialVersionUID = 1L;
        @XmlAttribute(name = "parse", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
        @NotNull
        protected boolean parse;
        @XmlAttribute(name = "generate", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
        @NotNull
        protected boolean generate;

        /**
         * Gets the value of the parse property.
         * 
         */
        @NotNull
        public boolean isParse() {
            return parse;
        }

        /**
         * Sets the value of the parse property.
         * 
         */
        public void setParse(
            @NotNull
            boolean value) {
            this.parse = value;
        }

        /**
         * Gets the value of the generate property.
         * 
         */
        @NotNull
        public boolean isGenerate() {
            return generate;
        }

        /**
         * Sets the value of the generate property.
         * 
         */
        public void setGenerate(
            @NotNull
            boolean value) {
            this.generate = value;
        }

    }

}
