//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}PartyId" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}PartyRef" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}CollaborationRole" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Certificate" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}SecurityDetails" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}DeliveryChannel" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Transport" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}DocExchange" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}OverrideMshActionBinding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="partyName" use="required" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}non-empty-string" /&gt;
 *       &lt;attribute name="defaultMshChannelId" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="defaultMshPackageId" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "partyId",
    "partyRef",
    "collaborationRole",
    "certificate",
    "securityDetails",
    "deliveryChannel",
    "transport",
    "docExchange",
    "overrideMshActionBinding"
})
@XmlRootElement(name = "PartyInfo")
public class PartyInfo
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "PartyId", required = true)
    @NotNull
    protected List<@NotNull PartyId> partyId;
    @XmlElement(name = "PartyRef", required = true)
    @NotNull
    protected List<@NotNull PartyRef> partyRef;
    @XmlElement(name = "CollaborationRole", required = true)
    @NotNull
    protected List<@NotNull CollaborationRole> collaborationRole;
    @XmlElement(name = "Certificate")
    @NotNull
    protected List<@NotNull Certificate> certificate;
    @XmlElement(name = "SecurityDetails")
    @NotNull
    protected List<@NotNull SecurityDetails> securityDetails;
    @XmlElement(name = "DeliveryChannel", required = true)
    @NotNull
    protected List<@NotNull DeliveryChannel> deliveryChannel;
    @XmlElement(name = "Transport", required = true)
    @NotNull
    protected List<@NotNull Transport> transport;
    @XmlElement(name = "DocExchange", required = true)
    @NotNull
    protected List<@NotNull DocExchange> docExchange;
    @XmlElement(name = "OverrideMshActionBinding")
    @NotNull
    protected List<@NotNull OverrideMshActionBinding> overrideMshActionBinding;
    @XmlAttribute(name = "partyName", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @NotNull
    protected String partyName;
    @XmlAttribute(name = "defaultMshChannelId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @NotNull
    protected Object defaultMshChannelId;
    @XmlAttribute(name = "defaultMshPackageId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    @NotNull
    protected Object defaultMshPackageId;

    /**
     * Gets the value of the partyId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyId }
     * 
     * 
     */
    @NotNull
    public List<@NotNull PartyId> getPartyId() {
        if (partyId == null) {
            partyId = new ArrayList<PartyId>();
        }
        return this.partyId;
    }

    /**
     * Gets the value of the partyRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the partyRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPartyRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PartyRef }
     * 
     * 
     */
    @NotNull
    public List<@NotNull PartyRef> getPartyRef() {
        if (partyRef == null) {
            partyRef = new ArrayList<PartyRef>();
        }
        return this.partyRef;
    }

    /**
     * Gets the value of the collaborationRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the collaborationRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCollaborationRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CollaborationRole }
     * 
     * 
     */
    @NotNull
    public List<@NotNull CollaborationRole> getCollaborationRole() {
        if (collaborationRole == null) {
            collaborationRole = new ArrayList<CollaborationRole>();
        }
        return this.collaborationRole;
    }

    /**
     * Gets the value of the certificate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the certificate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCertificate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Certificate }
     * 
     * 
     */
    @NotNull
    public List<@NotNull Certificate> getCertificate() {
        if (certificate == null) {
            certificate = new ArrayList<Certificate>();
        }
        return this.certificate;
    }

    /**
     * Gets the value of the securityDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityDetails }
     * 
     * 
     */
    @NotNull
    public List<@NotNull SecurityDetails> getSecurityDetails() {
        if (securityDetails == null) {
            securityDetails = new ArrayList<SecurityDetails>();
        }
        return this.securityDetails;
    }

    /**
     * Gets the value of the deliveryChannel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryChannel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryChannel }
     * 
     * 
     */
    @NotNull
    public List<@NotNull DeliveryChannel> getDeliveryChannel() {
        if (deliveryChannel == null) {
            deliveryChannel = new ArrayList<DeliveryChannel>();
        }
        return this.deliveryChannel;
    }

    /**
     * Gets the value of the transport property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transport property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransport().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Transport }
     * 
     * 
     */
    @NotNull
    public List<@NotNull Transport> getTransport() {
        if (transport == null) {
            transport = new ArrayList<Transport>();
        }
        return this.transport;
    }

    /**
     * Gets the value of the docExchange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the docExchange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDocExchange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocExchange }
     * 
     * 
     */
    @NotNull
    public List<@NotNull DocExchange> getDocExchange() {
        if (docExchange == null) {
            docExchange = new ArrayList<DocExchange>();
        }
        return this.docExchange;
    }

    /**
     * Gets the value of the overrideMshActionBinding property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the overrideMshActionBinding property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOverrideMshActionBinding().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OverrideMshActionBinding }
     * 
     * 
     */
    @NotNull
    public List<@NotNull OverrideMshActionBinding> getOverrideMshActionBinding() {
        if (overrideMshActionBinding == null) {
            overrideMshActionBinding = new ArrayList<OverrideMshActionBinding>();
        }
        return this.overrideMshActionBinding;
    }

    /**
     * Gets the value of the partyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @NotNull
    public String getPartyName() {
        return partyName;
    }

    /**
     * Sets the value of the partyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyName(
        @NotNull
        String value) {
        this.partyName = value;
    }

    /**
     * Gets the value of the defaultMshChannelId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @NotNull
    public Object getDefaultMshChannelId() {
        return defaultMshChannelId;
    }

    /**
     * Sets the value of the defaultMshChannelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDefaultMshChannelId(
        @NotNull
        Object value) {
        this.defaultMshChannelId = value;
    }

    /**
     * Gets the value of the defaultMshPackageId property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    @NotNull
    public Object getDefaultMshPackageId() {
        return defaultMshPackageId;
    }

    /**
     * Sets the value of the defaultMshPackageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDefaultMshPackageId(
        @NotNull
        Object value) {
        this.defaultMshPackageId = value;
    }

}
