//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for persistenceLevel.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="persistenceLevel.type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}Name"&gt;
 *     &lt;enumeration value="none"/&gt;
 *     &lt;enumeration value="transient"/&gt;
 *     &lt;enumeration value="persistent"/&gt;
 *     &lt;enumeration value="transient-and-persistent"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "persistenceLevel.type")
@XmlEnum
public enum PersistenceLevelType {

    @XmlEnumValue("none")
    NONE("none"),
    @XmlEnumValue("transient")
    TRANSIENT("transient"),
    @XmlEnumValue("persistent")
    PERSISTENT("persistent"),
    @XmlEnumValue("transient-and-persistent")
    TRANSIENT_AND_PERSISTENT("transient-and-persistent");
    private final String value;

    PersistenceLevelType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PersistenceLevelType fromValue(String v) {
        for (PersistenceLevelType c: PersistenceLevelType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
