//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Retries" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="RetryInterval" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/&gt;
 *         &lt;element name="MessageOrderSemantics" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}messageOrderSemantics.type"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "retries",
    "retryInterval",
    "messageOrderSemantics"
})
@XmlRootElement(name = "ReliableMessaging")
public class ReliableMessaging
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Retries")
    protected BigInteger retries;
    @XmlElement(name = "RetryInterval")
    protected Duration retryInterval;
    @XmlElement(name = "MessageOrderSemantics", required = true)
    @XmlSchemaType(name = "Name")
    @NotNull
    protected MessageOrderSemanticsType messageOrderSemantics;

    /**
     * Gets the value of the retries property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRetries() {
        return retries;
    }

    /**
     * Sets the value of the retries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRetries(BigInteger value) {
        this.retries = value;
    }

    /**
     * Gets the value of the retryInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getRetryInterval() {
        return retryInterval;
    }

    /**
     * Sets the value of the retryInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setRetryInterval(Duration value) {
        this.retryInterval = value;
    }

    /**
     * Gets the value of the messageOrderSemantics property.
     * 
     * @return
     *     possible object is
     *     {@link MessageOrderSemanticsType }
     *     
     */
    @NotNull
    public MessageOrderSemanticsType getMessageOrderSemantics() {
        return messageOrderSemantics;
    }

    /**
     * Sets the value of the messageOrderSemantics property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageOrderSemanticsType }
     *     
     */
    public void setMessageOrderSemantics(
        @NotNull
        MessageOrderSemanticsType value) {
        this.messageOrderSemantics = value;
    }

}
