//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statusValue.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="statusValue.type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="agreed"/&gt;
 *     &lt;enumeration value="signed"/&gt;
 *     &lt;enumeration value="proposed"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "statusValue.type")
@XmlEnum
public enum StatusValueType {

    @XmlEnumValue("agreed")
    AGREED("agreed"),
    @XmlEnumValue("signed")
    SIGNED("signed"),
    @XmlEnumValue("proposed")
    PROPOSED("proposed");
    private final String value;

    StatusValueType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusValueType fromValue(String v) {
        for (StatusValueType c: StatusValueType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
