//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for syncReplyMode.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="syncReplyMode.type"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="mshSignalsOnly"/&gt;
 *     &lt;enumeration value="responseOnly"/&gt;
 *     &lt;enumeration value="signalsAndResponse"/&gt;
 *     &lt;enumeration value="signalsOnly"/&gt;
 *     &lt;enumeration value="none"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "syncReplyMode.type")
@XmlEnum
public enum SyncReplyModeType {

    @XmlEnumValue("mshSignalsOnly")
    MSH_SIGNALS_ONLY("mshSignalsOnly"),
    @XmlEnumValue("responseOnly")
    RESPONSE_ONLY("responseOnly"),
    @XmlEnumValue("signalsAndResponse")
    SIGNALS_AND_RESPONSE("signalsAndResponse"),
    @XmlEnumValue("signalsOnly")
    SIGNALS_ONLY("signalsOnly"),
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    SyncReplyModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SyncReplyModeType fromValue(String v) {
        for (SyncReplyModeType c: SyncReplyModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
