//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransportProtocol" type="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}protocol.type"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}AccessAuthentication" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}Endpoint" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}TransportServerSecurity" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportProtocol",
    "accessAuthentication",
    "endpoint",
    "transportServerSecurity"
})
@XmlRootElement(name = "TransportReceiver")
public class TransportReceiver
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TransportProtocol", required = true)
    @NotNull
    protected ProtocolType transportProtocol;
    @XmlElement(name = "AccessAuthentication")
    @XmlSchemaType(name = "NMTOKEN")
    @NotNull
    protected List<@NotNull AccessAuthenticationType> accessAuthentication;
    @XmlElement(name = "Endpoint", required = true)
    @NotNull
    protected List<@NotNull Endpoint> endpoint;
    @XmlElement(name = "TransportServerSecurity")
    protected TransportServerSecurity transportServerSecurity;

    /**
     * Gets the value of the transportProtocol property.
     * 
     * @return
     *     possible object is
     *     {@link ProtocolType }
     *     
     */
    @NotNull
    public ProtocolType getTransportProtocol() {
        return transportProtocol;
    }

    /**
     * Sets the value of the transportProtocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProtocolType }
     *     
     */
    public void setTransportProtocol(
        @NotNull
        ProtocolType value) {
        this.transportProtocol = value;
    }

    /**
     * Gets the value of the accessAuthentication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the accessAuthentication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAccessAuthentication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AccessAuthenticationType }
     * 
     * 
     */
    @NotNull
    public List<@NotNull AccessAuthenticationType> getAccessAuthentication() {
        if (accessAuthentication == null) {
            accessAuthentication = new ArrayList<AccessAuthenticationType>();
        }
        return this.accessAuthentication;
    }

    /**
     * Gets the value of the endpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the endpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEndpoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Endpoint }
     * 
     * 
     */
    @NotNull
    public List<@NotNull Endpoint> getEndpoint() {
        if (endpoint == null) {
            endpoint = new ArrayList<Endpoint>();
        }
        return this.endpoint;
    }

    /**
     * Gets the value of the transportServerSecurity property.
     * 
     * @return
     *     possible object is
     *     {@link TransportServerSecurity }
     *     
     */
    public TransportServerSecurity getTransportServerSecurity() {
        return transportServerSecurity;
    }

    /**
     * Sets the value of the transportServerSecurity property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportServerSecurity }
     *     
     */
    public void setTransportServerSecurity(TransportServerSecurity value) {
        this.transportServerSecurity = value;
    }

}
