//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.04 at 02:30:27 PM CEST 
//


package org.oasis_open.committees.ebxml_cppa.schema.cpp_cpa_2_0;

import java.io.Serializable;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import com.github.labai.jsr305x.api.NotNull;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}TransportSender" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd}TransportReceiver" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="transportId" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transportSender",
    "transportReceiver"
})
@XmlRootElement(name = "Transport")
public class Transport
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "TransportSender")
    protected TransportSender transportSender;
    @XmlElement(name = "TransportReceiver")
    protected TransportReceiver transportReceiver;
    @XmlAttribute(name = "transportId", namespace = "http://www.oasis-open.org/committees/ebxml-cppa/schema/cpp-cpa-2_0.xsd", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @NotNull
    protected String transportId;

    /**
     * Gets the value of the transportSender property.
     * 
     * @return
     *     possible object is
     *     {@link TransportSender }
     *     
     */
    public TransportSender getTransportSender() {
        return transportSender;
    }

    /**
     * Sets the value of the transportSender property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportSender }
     *     
     */
    public void setTransportSender(TransportSender value) {
        this.transportSender = value;
    }

    /**
     * Gets the value of the transportReceiver property.
     * 
     * @return
     *     possible object is
     *     {@link TransportReceiver }
     *     
     */
    public TransportReceiver getTransportReceiver() {
        return transportReceiver;
    }

    /**
     * Sets the value of the transportReceiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportReceiver }
     *     
     */
    public void setTransportReceiver(TransportReceiver value) {
        this.transportReceiver = value;
    }

    /**
     * Gets the value of the transportId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @NotNull
    public String getTransportId() {
        return transportId;
    }

    /**
     * Sets the value of the transportId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransportId(
        @NotNull
        String value) {
        this.transportId = value;
    }

}
